# Generated by Django 5.0.4 on 2026-02-28 12:34

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Marka Adı')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='URL')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/', verbose_name='Logo')),
                ('website', models.URLField(blank=True, verbose_name='Web Sitesi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Sıra')),
            ],
            options={
                'verbose_name': 'Marka',
                'verbose_name_plural': 'Markalar',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Sertifika')),
                ('code', models.CharField(help_text='Örnek: EN 397', max_length=50, verbose_name='Kod')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
            ],
            options={
                'verbose_name': 'Sertifika',
                'verbose_name_plural': 'Sertifikalar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SliderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='Alt Başlık')),
                ('tag', models.CharField(blank=True, help_text='Örnek: ✅ CE Sertifikalı Ürünler', max_length=80, verbose_name='Etiket')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='slider/', verbose_name='Arka Plan Görseli')),
                ('background_color', models.CharField(blank=True, help_text='background CSS değeri', max_length=200, verbose_name='Arka Plan Rengi (CSS)')),
                ('primary_btn_text', models.CharField(blank=True, max_length=60, verbose_name='Birincil Buton Metni')),
                ('primary_btn_url', models.CharField(blank=True, max_length=200, verbose_name='Birincil Buton URL')),
                ('secondary_btn_text', models.CharField(blank=True, max_length=60, verbose_name='İkincil Buton Metni')),
                ('secondary_btn_url', models.CharField(blank=True, max_length=200, verbose_name='İkincil Buton URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Sıra')),
            ],
            options={
                'verbose_name': 'Slider',
                'verbose_name_plural': 'Slider Öğeleri',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Kategori Adı')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='URL')),
                ('icon', models.CharField(blank=True, help_text='Örnek: ⛑️ ya da fa-hard-hat', max_length=50, verbose_name='İkon (emoji/fa)')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Görsel')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Sıra')),
                ('meta_title', models.CharField(blank=True, max_length=60, verbose_name='SEO Başlık')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='SEO Açıklama')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='products.category', verbose_name='Üst Kategori')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ürün Adı')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='URL')),
                ('short_description', models.TextField(help_text='Kart görünümünde gösterilir', max_length=300, verbose_name='Kısa Açıklama')),
                ('description', ckeditor.fields.RichTextField(blank=True, verbose_name='Detaylı Açıklama')),
                ('usage_areas', ckeditor.fields.RichTextField(blank=True, verbose_name='Kullanım Alanları')),
                ('care_instructions', ckeditor.fields.RichTextField(blank=True, verbose_name='Bakım ve Depolama')),
                ('specifications', models.JSONField(blank=True, default=dict, help_text='{"Standart": "EN 397", "Materyal": "HDPE", ...}', verbose_name='Teknik Özellikler')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='products/thumbnails/', verbose_name='Ana Görsel')),
                ('badge', models.CharField(blank=True, choices=[('', 'Rozetsiz'), ('yeni', 'Yeni'), ('populer', 'Popüler'), ('ce', 'CE Belgeli')], default='', max_length=20, verbose_name='Rozet')),
                ('meta_title', models.CharField(blank=True, max_length=60, verbose_name='SEO Başlık')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='SEO Açıklama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Öne Çıkan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturuldu')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellendi')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.brand', verbose_name='Marka')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category', verbose_name='Kategori')),
                ('certificates', models.ManyToManyField(blank=True, to='products.certificate', verbose_name='Sertifikalar')),
                ('related_products', models.ManyToManyField(blank=True, to='products.product', verbose_name='İlgili Ürünler')),
            ],
            options={
                'verbose_name': 'Ürün',
                'verbose_name_plural': 'Ürünler',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/', verbose_name='Görsel')),
                ('alt_text', models.CharField(blank=True, max_length=150, verbose_name='Alt Metin')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Sıra')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Ürün Görseli',
                'verbose_name_plural': 'Ürün Görselleri',
                'ordering': ['order'],
            },
        ),
    ]
