# Generated by Django 5.0.4 on 2026-02-28 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Ad Soyad')),
                ('company', models.CharField(blank=True, max_length=150, verbose_name='Şirket')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('subject', models.CharField(choices=[('teklif', 'Fiyat Teklifi'), ('urun-bilgi', 'Ürün Bilgisi'), ('kurumsal', 'Kurumsal Sözleşme'), ('danismanlik', 'ISG Danışmanlığı'), ('sertifika', 'Sertifika Talebi'), ('diger', 'Diğer')], max_length=30, verbose_name='Konu')),
                ('products_of_interest', models.JSONField(blank=True, default=list, verbose_name='İlgilenilen Ürünler')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('status', models.CharField(choices=[('new', 'Yeni'), ('in_progress', 'İşlemde'), ('done', 'Tamamlandı')], default='new', max_length=20, verbose_name='Durum')),
                ('note', models.TextField(blank=True, verbose_name='Admin Notu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Gönderildi')),
            ],
            options={
                'verbose_name': 'İletişim Mesajı',
                'verbose_name_plural': 'İletişim Mesajları',
                'ordering': ['-created_at'],
            },
        ),
    ]
