# Generated by Django 5.0.4 on 2026-02-28 12:34

import ckeditor_uploader.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategori')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='URL')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Sıra')),
            ],
            options={
                'verbose_name': 'Blog Kategorisi',
                'verbose_name_plural': 'Blog Kategorileri',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='URL')),
                ('excerpt', models.TextField(help_text='Kart ve SEO açıklaması için kullanılır', max_length=300, verbose_name='Özet')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='İçerik')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='blog/thumbnails/', verbose_name='Kapak Görseli')),
                ('status', models.CharField(choices=[('draft', 'Taslak'), ('published', 'Yayınlandı')], default='draft', max_length=20, verbose_name='Durum')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Öne Çıkan')),
                ('read_time', models.PositiveSmallIntegerField(default=5, verbose_name='Okuma Süresi (dk)')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Yayın Tarihi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturuldu')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellendi')),
                ('meta_title', models.CharField(blank=True, max_length=60, verbose_name='SEO Başlık')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='SEO Açıklama')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Yazar')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.blogcategory', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Blog Yazısı',
                'verbose_name_plural': 'Blog Yazıları',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
